### PR TITLE
Modify Type of TotalPaidMinutesUsed

### PR DESCRIPTION
**Pull request by ruchikawa**
## Problem
I got error when I use gihub-billing-exporter.
The error message is as follows.

```
$ ./github-billing-expoerter server -t MY_TOKEN -o MY_ORGS
2021/03/04 19:39:50 json: cannot unmarshal number into Go struct field actionsBilling.total_paid_minutes_used of type string
```

The problem is that when the return value of total_paid_minutes_used is 0, as shown below, Golang Interprets it as Integer
Maybe, if the return value is non-zero, then strconvParseFloat will convert the value to Float64.

```
% curl -k -s -u ruchikawa:MASKED  'https://api.github.com/orgs/masked/settings/billing/actions'
{
  "total_minutes_used": 2403,
  "total_paid_minutes_used": 0,
  "included_minutes": 3000,
  "minutes_used_breakdown": {
    "UBUNTU": 2403
  }
}
```

## Solution
The reason is that the return value of `total_paid_minutes_used` will return a number of minutes, so I thought the type should be an integer.
If total_paid_minutes_used returns a non-integer value, this fix is not appropriate.
But I coudn't check the return of value, because Our organization returns `total_paid_minutes_used` as 0.

## Before & After
I did not have time to write the test.
```
# before
% go run main.go server -t MY_TOKEN -o MY_ORGS
2021/03/04 22:25:29 json: cannot unmarshal number into Go struct field actionsBilling.total_paid_minutes_used of type string
exit status 1
```

```
# After
## run gihub-billing-exporter
% go run main.go server -t MY_TOKEN -o MY_ORGS

##  curl with Another terminal
% curl localhost:9999/metrics | grep total_paid_minutes_used
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6985    0  6985    0     0  6821k      0 --:--:-- --:--:-- --:--:-- 6821k
# HELP total_paid_minutes_used github actions total paid minutes used
# TYPE total_paid_minutes_used gauge
total_paid_minutes_used{owner="MY_OWNER"} 0
``

### CODE REVIEW

**Comment by nashiox** [comment]
@ruchikawa Thank you for sending your pull request!

I understand the purpose of your PR.

I haven't reproduced it now, but at that time I implemented it thinking that it was a bug in the GitHub API.
I investigated whether it was fixed on the GitHub API side or if there were any conditions, but so far I could not find any evidence.

Please give me a little more time to check.

**Comment by nashiox** [comment]
@ruchikawa Thanks for waiting.

Although it is a specification that is not written in the official document of GitHub, I found that `total_paid_minutes_used` is returned as an integer when it is `0`, and as a `string` in other cases.

```
### case 0
{
  "total_minutes_used": 0,
  "total_paid_minutes_used": 0,
  "included_minutes": 2000,
  "minutes_used_breakdown": {

  }
}

### other cases
{
  "total_minutes_used": 3028,
  "total_paid_minutes_used": "28.0",
  "included_minutes": 3000,
  "minutes_used_breakdown": {
    "UBUNTU": 3028
  }
}
```

It may be officially fixed in the future, but it needs to be changed to use `json.Number`.

Could you fix it?

**Comment by ruchikawa** [comment]
@nashiox
Sorry for the late reply.

I was trying to imagine why you treated `total_paid_minutes_used` as string, and using strconv.
The bad prediction came true...
Sorry, but There is no way to check the return value from Github.
Because `total_paid_minutes_used` always return '0' to me...

OK, I'll try to fix them. ( maybe it takes a time. )
Now, I'm thinking of setting the type of `total_paid_minutes_used` to `json.Number` to resolve this issue.

**Comment by ruchikawa** [comment]
@nashiox Hi, Sorry for the late reply.

I fixed the code.
The type of `TotalPaidMinutesUsed`  was changed to json.Number.
I'm keeping up with the latest changes from main branch.

**Review by nashiox — APPROVED** [review]
Thanks.

**Pull request merged**
